variables:
  SERVICE_NAME: front-service
  BUILD_CONTEXT: ./frontend/
  K8S_PATH: ./infra/k8s/apis/api-front.yml
build_front:
  variables:
    SERVICE_NAME: front-service
    BUILD_CONTEXT: ./frontend/
    K8S_PATH: ./infra/k8s/apis/api-front.yml
    NGINX_CONF: nginx.conf
  rules:
    - changes:
        - frontend/**/*
        - frontend/*
      when: always
    - when: never
  stage: build
  tags:
    - $GITLAB_USER_EMAIL
  script:
    - echo "🔨 Docker 이미지 빌드 및 테스트 중..."
    - docker build -t ${DOCKERHUB_USERNAME:-default}/$REGISTRY_PATH-${SERVICE_NAME}:$IMAGE_TAG  ${BUILD_CONTEXT}
    - docker images
    #- echo "✅ 빌드 완료: $IMAGE_NAME:$IMAGE_TAG

build_nginx:
  variables:
    SERVICE_NAME: frontend-nginx
    FRONT_NAME: front-service
    BUILD_CONTEXT: ./infra/nginx
    K8S_PATH: ./infra/k8s/infras/nginx-frontend.yml
    FRONTEND_IMAGE: ${DOCKERHUB_USERNAME:-default}/$REGISTRY_PATH-${FRONT_NAME}:$IMAGE_TAG ${BUILD_CONTEXT}
    NGINX_CONF: nginx.conf
  rules:
    - changes:
        - frontend/**/*
  needs: [build_front]
  stage: build
  tags:
    - $GITLAB_USER_EMAIL
  script:
    - docker images
    - echo "🔨 Docker 이미지 빌드 및 테스트 중..."
    - docker build --build-arg FRONTEND_IMAGE=${DOCKERHUB_USERNAME}/$REGISTRY_PATH-${FRONT_NAME}:$IMAGE_TAG --build-arg SERVER_DOMAIN=$SERVER_DOMAIN --build-arg CERT_DOMAIN=$CERT_DOMAIN -t ${DOCKERHUB_USERNAME:-default}/$REGISTRY_PATH-${SERVICE_NAME}:$IMAGE_TAG $BUILD_CONTEXT

push_front:
  variables:
    SERVICE_NAME: frontend-nginx
    BUILD_CONTEXT: ./infra/nginx
    K8S_PATH: infra/k8s/infras/nginx-frontend.yml
    NGINX_CONF: nginx.conf
  extends: .backend-default-push
  needs: [build_nginx]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - frontend/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"'
      changes:
        - frontend/**/*
      when: manual
    - when: never

deploy_front:
  variables:
    SERVICE_NAME: frontend-nginx
    BUILD_CONTEXT: ./infra/nginx
    K8S_PATH: infra/k8s/infras/nginx-frontend.yml
    NGINX_CONF: nginx.conf
  extends: .backend-default-deploy
  needs: [push_front]
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - frontend/**/*
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"' # 수동 실행도 허용하려면
      changes:
        - frontend/**/*
      when: manual
    - when: never
