spring:
  application:
    name: springcloud-gateway
  profiles:
    active: docker

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter.RouteToRequestUrlFilter: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
---
spring:
  cloud:
    gateway:
      routes:
        - id: backbone-service
          uri: http://backbone-service:8080
          predicates:
            - Path=/api/backbone/**
          filters:
            - StripPrefix=2

        - id: game-kjh-service
          uri: http://gameKJH-service:8080
          predicates:
            - Path=/api/game/kjh/**
          filters:
            - StripPrefix=3

        - id: game-cjm-service
          uri: http://gameCJM-service:8080
          predicates:
            - Path=/api/game/cjm/**
          filters:
            - StripPrefix=3

        - id: game-kyh-service
          uri: http://gameKYH-service:8080
          predicates:
            - Path=/api/game/kyh/**
          filters:
            - StripPrefix=3

        - id: game-lsr-service
          uri: http://gameLSR-service:8080
          predicates:
            - Path=/api/game/lsr/**
          filters:
            - StripPrefix=3

        - id: game-ojs-service
          uri: http://gameOJS-service:8080
          predicates:
            - Path=/api/game/ojs/**
          filters:
            - StripPrefix=3

        - id: game-ydg-service
          uri: http://gameYDG-service:8080
          predicates:
            - Path=/api/game/ydg/**
          filters:
            - StripPrefix=3
#verify-url: http://member-service:8080/auth/internal/verify-token


server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-GATEWAY, k8s
      routes:
        - id: backbone-service
          uri: http://backbone-service:8080
          predicates:
            - Path=/api/backbone/**
          filters:
            - StripPrefix=2

        - id: game-kjh-service
          uri: http://gameKJH-service:8080
          predicates:
            - Path=/api/game/kjh/**
          filters:
            - StripPrefix=3

        - id: game-cjm-service
          uri: http://gameCJM-service:8080
          predicates:
            - Path=/api/game/cjm/**
          filters:
            - StripPrefix=3

        - id: game-kyh-service
          uri: http://gameKYH-service:8080
          predicates:
            - Path=/api/game/kyh/**
          filters:
            - StripPrefix=3

        - id: game-lsr-service
          uri: http://gameLSR-service:8080
          predicates:
            - Path=/api/game/lsr/**
          filters:
            - StripPrefix=3

        - id: game-ojs-service
          uri: http://gameOJS-service:8080
          predicates:
            - Path=/api/game/ojs/**
          filters:
            - StripPrefix=3

        - id: game-ydg-service
          uri: http://gameYDG-service:8080
          predicates:
            - Path=/api/game/ydg/**
          filters:
            - StripPrefix=3

#verify-url: http://member-service:8080/auth/internal/verify-token

server:
  port: 8080
